language: generic

os: linux

services:
 - docker

jobs:
  include:
    - name: build and upload docker image
      script:
        - docker --version # print the version for logging
        - docker build -t udagram-user .
        - docker tag udagram-user langerca/udagram-user:latest
      after_success:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker push langerca/udagram-user:latest
